### ISSUE TITLE
Some questions on usage in README.md

### ISSUE THREAD

**Issue by iamzhout** [desdic/fluent-plugin-jsontcp#1]
Hi desdic,

I have some questions on the usage, 
1. _utc_ is useless?
2. _buffer_chunk_limit 1k_  is too small?

```
<match rsyslog.** legacyrsyslog.**>
  type jsontcp
  format json
  utc
  port 3540
  buffer_type file
  buffer_path /var/log/td-agent/fluent_buffer0
  buffer_chunk_limit 1k
  buffer_queue_limit 8192
  flush_interval 1s
</match>
```

Thanks,
Tao

**Comment by desdic** [comment]
Hi,
1. utc should tell fluentd to always give timestamps in UTC. Otherwise it will give the localtime. The plugin runs on a machine with UTC so I haven't testet of the option really matters
2. Its just an example. In real world our default buffer is set to 16m

/Kim

**Comment by iamzhout** [comment]
Why I am asking about the usage for _utc_ is that when I start td-agent in command line, it will prompt below warning message, and it seems to me that this item will be ignored by fluentd.

```
2015-12-30 18:51:11 +0000 [warn]: parameter 'utc' in <match **>
  @type jsontcp
  format json
  utc
  host 1.2.3.4
  port 5678
  buffer_type file
  buffer_path /var/log/td-agent/fluent_buffer0
  buffer_chunk_limit 8m
  buffer_queue_limit 2
  flush_interval 5s
</match> is not used.
```

Seems that only **TimeSlicedOutput** supports _utc_ configuration, in fluentd/lib/fluent/output.rb.

**Comment by desdic** [comment]
Hmm I'm not getting a warning here with fluentd 0.12.19 but if your timestamp is already UTC just remove it. Btw. the config we use in production is this one:

<match rsyslog.**>
   type jsontcp
   utc
   port  3540
   format json
   buffer_type file
   buffer_path /var/log/td-agent/fluent_buffer0
   buffer_chunk_limit 32m
   buffer_queue_limit 8192
   retry_wait 1s
   retry_limit 86400
   max_retry_wait 60s
   disable_retry_limit = true
   flush_interval 5s
   <secondary>
   type file
   path /var/log/td-agent/failed_fluent_records0
   </secondary>
</match>
