### ISSUE TITLE
always getting "queue size exceeds limit" warning message

### ISSUE THREAD

**Issue by iamzhout** [desdic/fluent-plugin-jsontcp#2]
Hi Kim,

When using jsontcp plugin, I always getting below warning message, though the log throughput is quite low. I have configured _buffer_chunk_limit to 16m_, but it is still the same.

```
2015-12-30 10:17:01 +0000 [warn]: emit transaction failed: error_class=Fluent::BufferQueueLimitError error="queue size exceeds limit"
2015-12-30 10:17:01 +0000 [warn]: suppressed same stacktrace
```

As new to fluentd, I don't have quite much idea at this time.
I do have asked google if he can give some hint and got some relevant results as below, but seems still can not explain the problem I have.
[https://github.com/fluent/fluentd/issues/523](https://github.com/fluent/fluentd/issues/523)  |  [https://github.com/fluent/fluentd/issues/343](https://github.com/fluent/fluentd/issues/343)  |  [http://buta9999.hatenablog.jp/entry/20131120/1384958564](http://buta9999.hatenablog.jp/entry/20131120/1384958564)

Do you also have the same problem? Or if you could give me some hint on why the error, or how to change fluentd configuration to quiet mode to not to print this warning message out?

Regards,
Tao

**Comment by iamzhout** [comment]
after checking fluentd source in buffer.rb, seems the problem is running fluentd queue size exceeds _buffer_queue_limit_, but even I enlarge _buffer_queue_limit_ value to 256, still the same warning message at startup.
and I tried to add _buffer_queue_full_action block_, not any change. :-(

the fluentd version I use is 0.12.12.

**Comment by desdic** [comment]
I'm not getting this with

<match rsyslog.**>
   type jsontcp
   utc
   port  3540
   format json
   buffer_type file
   buffer_path /var/log/td-agent/fluent_buffer0
   buffer_chunk_limit 32m
   buffer_queue_limit 8192
   retry_wait 1s
   retry_limit 86400
   max_retry_wait 60s
   disable_retry_limit = true
   flush_interval 5s
   <secondary>
   type file
   path /var/log/td-agent/failed_fluent_records0
   </secondary>
</match>

and fluentd 0.12.19. Can you try with the limits of my config ?

**Comment by iamzhout** [comment]
Thanks Kim,

I have tried your production config, but still getting a lot of warn msg saying "queue size exceeds limit" :-(

I will have a try on fluentd 0.12.19 days later, and report the result then.

Regards,
Tao

**Comment by desdic** [comment]
Hmm :( I don't normally work with fluentd I just wrote the plugin but can you wait until after newyear and I'll talk to the guy who configured our setup ? Also give 0.12.19 a try :)

**Comment by iamzhout** [comment]
I will have vacation for New Year's Day holiday, and will do more try after that. 
Thanks and happy new year. :)

**Comment by desdic** [comment]
Thank you and may you also have a happy new year :)

**Comment by iamzhout** [comment]
I have tried to restart the origin 0.12.12 env, and also tried to upgrade fluentd version to latest 0.12.19.
Now both 0.12.12 and 0.12.19 all works fine without previous "queue size exceeds limit" warn message.

So maybe it is caused by some env related problems without a clean startup.
I think this issue could be closed now.

Thanks Kim

**Comment by desdic** [comment]
That sounds very good :) thank you for getting back to me with feedback
